import org.jetbrains.compose.desktop.application.dsl.TargetFormat
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

// Lyrico Desktop — Compose Multiplatform Desktop application module.
//
// This module used to be an Android application. The Android Gradle Plugin, the NDK/CMake
// integration, the signing/splits config and the Android-only dependency set are gone; the native
// libraries are built out-of-band by scripts/build-native.ps1 into build/native/windows-x64/ and are
// loaded from the JVM at runtime (see lyrico-audiotag's NativeLibraryLoader).
//
// Source layout during the port (PLAN.md phase 2 → 4):
//   src/main/kotlin  — desktop sources (this phase: the application shell only)
//   src/main/java    — the original Android source tree; still unconsumed. Files are moved over with
//                      `git mv` as they are ported (phase 3/4), and the directory is deleted at the
//                      end of phase 4 together with AndroidManifest.xml and src/main/res.
//   src/test/java    — the original Android unit tests; unconsumed, same migration path.
plugins {
    alias(libs.plugins.kotlin.jvm)
    alias(libs.plugins.kotlin.compose)
    // The metadata/plugin model classes are @Serializable (PluginManifest declares custom
    // serializers), so the compiler plugin has to be applied — the runtime library alone only
    // provides the annotations.
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.compose.multiplatform)
    alias(libs.plugins.ksp)
}

group = "com.lonx.lyrico"

// Remember to bump these when releasing (mirrors the Android module's versionName/versionCode).
val baseVersionName = "1.6.0"
val baseVersionCode = 20

fun gitCommitHash(): Provider<String> = providers.exec {
    commandLine("git", "rev-parse", "--short", "HEAD")
    isIgnoreExitValue = true
}.standardOutput.asText.map { it.trim().ifEmpty { "unknown" } }.orElse("unknown")

version = "$baseVersionName-${gitCommitHash().get()}"

// Desktop equivalent of the Android module's BuildConfig: about 11 call sites in the UI/viewmodel
// layer read VERSION_NAME / VERSION_CODE / DEBUG, so the port needs this to exist before those files
// are migrated.
val generateBuildInfo = tasks.register("generateBuildInfo") {
    val outputDir = layout.buildDirectory.dir("generated/lyrico")
    val versionName = baseVersionName
    val versionCode = baseVersionCode
    val commit = gitCommitHash()
    val debugBuild = project.hasProperty("lyrico.debug")
    inputs.property("versionName", versionName)
    inputs.property("versionCode", versionCode)
    inputs.property("commit", commit)
    inputs.property("debugBuild", debugBuild)
    outputs.dir(outputDir)
    doLast {
        val dir = outputDir.get().asFile.resolve("com/lonx/lyrico")
        dir.mkdirs()
        dir.resolve("BuildInfo.kt").writeText(
            """
            // Generated by the :lyrico-app build — do not edit.
            package com.lonx.lyrico

            object BuildInfo {
                const val VERSION_NAME: String = "$versionName"
                const val VERSION_CODE: Long = ${versionCode}L
                const val COMMIT: String = "${commit.get()}"
                const val BUILD_TYPE: String = "desktop"
                const val DEBUG: Boolean = $debugBuild

                // Which GitHub repository the update check asks for releases. This fork builds a
                // Windows MSI/portable zip, so the Android upstream (Replica0110/Lyrico, whose
                // release assets are .apk) would offer a download this app cannot install
                // (PLAN.md section 5 decision).
                const val UPDATE_OWNER: String = "CN-Grace"
                const val UPDATE_REPO: String = "Lyrico-Desktop"
            }

            """.trimIndent(),
        )
    }
}

kotlin {
    jvmToolchain(21)
    sourceSets {
        main {
            // Owned by this build script. Note: never use setSrcDirs() here — the Compose resources
            // plugin registers its generated accessors (build/generated/compose/resourceGenerator)
            // into these same source sets, and replacing the list silently drops them, which shows
            // up as "Unresolved reference: resources" on every `Res.string.*` call site.
            kotlin.srcDir(generateBuildInfo)
        }
    }
}

// The legacy Android source tree is not part of the build yet (see the source layout note above).
// KGP adds src/main/java to the *Kotlin* source set, so it has to be cleared explicitly.
sourceSets {
    main { java.setSrcDirs(emptyList<String>()) }
    test { java.setSrcDirs(emptyList<String>()) }
}

tasks.withType<KotlinCompile>().configureEach {
    dependsOn(generateBuildInfo)
}

// The desktop app runs on a non-ASCII project path; keep the sources/intermediate text encoding
// explicit so that javac/kotlinc and any file IO agree with the GBK daemon setting in
// gradle.properties.
tasks.withType<JavaCompile>().configureEach {
    options.encoding = "UTF-8"
}

dependencies {
    implementation(project(":lyrico-audiotag"))

    // Persistence: Room's multiplatform runtime resolves to its JVM variant here, and the bundled
    // SQLite driver means the app carries its own SQLite instead of relying on a system install.
    implementation(libs.androidx.room.runtime)
    implementation(libs.androidx.sqlite.bundled)
    implementation(libs.androidx.datastore.preferences.core)
    ksp(libs.androidx.room.compiler)

    // Brings the Compose runtime, UI, foundation, material and Skiko (with the Skiko native
    // libraries for the current OS); Miuix's -desktop artifacts build on top of it.
    implementation(compose.desktop.currentOs)

    // The Android module generated `R.string.*` ids from src/main/res/values*/strings.xml. On desktop
    // the same role is played by Compose Multiplatform resources: the XML files live in
    // src/main/composeResources/values*/ and the build generates the `Res` object, so
    // `stringResource(Res.string.foo)` replaces `stringResource(R.string.foo)` at the call sites.
    implementation(compose.components.resources)

    // The ported screens are Miuix-based, but 22 of them also use a few Material 3 pieces that Miuix
    // does not provide (`TextButton`, `ButtonColors`, `Text`, `CircularProgressIndicator`,
    // `VerticalDivider`, `ripple()` for `LocalIndication`). Android got these from the app's
    // material3 dependency; on desktop they come from Compose Multiplatform's material3, which is the
    // same API for the common subset. Miuix's desktop artifacts do not pull it in transitively.
    implementation(compose.material3)

    implementation(libs.miuix.ui.desktop)
    implementation(libs.miuix.icons.desktop)
    implementation(libs.miuix.preference.desktop)
    implementation(libs.miuix.blur.desktop)

    // Cover art. The Android app loaded covers through Coil 3 with two custom components: a fetcher
    // that pulls embedded artwork out of an audio file through TagLib, and a fetcher for the user's
    // local artist-poster folder. Coil 3 is multiplatform (this artifact publishes a jvm variant), so
    // the same pipeline moves over unchanged apart from the file access underneath it. Without it the
    // list/album screens would silently lose every cover instead of failing.
    implementation(libs.coil.compose)

    implementation(libs.kotlinx.coroutines.core)
    implementation(libs.kotlinx.coroutines.swing)
    implementation(libs.kotlinx.serialization.json)

    // ViewModels on desktop. `androidx.lifecycle` needs to be a *compile* dependency: a
    // transitive dependency is not a compile classpath one — `androidx.lifecycle.ViewModel`/`viewModelScope` failed to resolve until this
    // was declared, which is exactly the kind of thing that looks like "desktop has no ViewModel".
    // The artifact is the JetBrains multiplatform publishing of the same `androidx.lifecycle`
    // classes, at the version Navigation Compose (desktop) itself resolves. Declaring Google's
    // androidx.lifecycle:lifecycle-viewmodel-compose here instead would be a *second* implementation
    // of the same packages on the classpath (Google's 2.11.0 publishes a -desktop variant too), and
    // then the winner is decided by classpath order.
    implementation(libs.jetbrains.lifecycle.viewmodel.compose)

    // The Android build got OkHttp from the app's DI graph; the tag layer needs it for
    // `PictureSource.UrlSource`, and the plugin-search runtime will reuse the same client.
    implementation(libs.okhttp)

    // DI: the Android app already used Koin (di/AppModule.kt), and Koin 4.x is multiplatform, so the
    // desktop graph is the same DSL. `koin-compose-viewmodel` is the drop-in for the Android artifact
    // the screens import `koinViewModel` from.
    implementation(libs.koin.core)
    implementation(libs.koin.compose)
    implementation(libs.koin.compose.viewmodel)

    // Navigation. The Android app used Compose Destinations (a KSP code generator) on top of
    // androidx.navigation; Compose Destinations publishes no jvm variant, so the port keeps the
    // Android-era navigation *library* (Navigation Compose, here in JetBrains' multiplatform build,
    // which does publish a desktop variant) and replaces only the generated layer with the typed
    // adapter in ui/navigation/ (see PLAN section 6 risk 3 for the resolution evidence).
    implementation(libs.navigation.compose)

    // Drag-to-reorder for the plugin list. Android pulled this in the same way (sh.calvin.reorderable);
    // the library publishes a real `jvm` variant, so the ported `PluginManagerScreen` keeps its
    // long-press-drag interaction instead of degrading to up/down buttons.
    implementation(libs.reorderable)

    // Markdown rendering for plugin-provided help text. Android used `com.github.jeziellago:compose-markdown`,
    // which is Android-only; this is the multiplatform renderer for the same job, and its `jvm`
    // variant depends on the IntelliJ markdown parser only -- no Compose version of its own, so it
    // renders through whatever runtime the app already provides. See `ui/components/MiuixMarkdown.kt`
    // for the colour/typography bridge (the library's own defaults read Material 3's theme, which this
    // app does not use).
    implementation(libs.multiplatform.markdown.renderer)

    // Chinese text handling: song sort keys are derived from pinyin, and the conversion modes
    // (simplified <-> traditional) run through OpenCC both when scanning and when encoding lyrics.
    implementation(libs.opencc4j)
    implementation(libs.pinyin)

    // Desktop UI tests render the real composables off-screen (no window needed) and assert on the
    // semantics tree — this is the harness the 24 screens of phase 4 will be ported against.
    testImplementation(kotlin("test"))
    // `Dispatchers.setMain` + virtual time: the view models run their flows on `viewModelScope`, which
    // needs a Main dispatcher in a plain JVM test (there is no Android looper here).
    testImplementation(libs.kotlinx.coroutines.test)
    testImplementation(libs.compose.ui.test)
}

// Room's annotation processor runs as a KSP symbol processor: it generates the `*_Impl` DAO
// classes and the JSON schema, which is committed under schemas/ so future migrations can be diffed.
ksp {
    arg("room.schemaLocation", "$projectDir/schemas")
    arg("room.generateKotlin", "true")
    arg("room.incremental", "true")
}

// Compose resources replace the Android resource pipeline (R.string ids are gone). The generated
// accessors keep the app's own package so ported call sites read `Res.string.song_title`.
compose.resources {
    packageOfResClass = "com.lonx.lyrico.resources"
    publicResClass = true
    generateResClass = org.jetbrains.compose.resources.ResourcesExtension.ResourceClassGeneration.Always
}

// The UI test renders through the same Miuix theme as the app and additionally asserts that the
// phase-1 native bridge loads in a plain JVM — so it needs the same lyrico.native.dir the app gets.
tasks.named<Test>("test") {
    val nativeDir = rootProject.layout.projectDirectory.dir("build/native/windows-x64").asFile.absolutePath
    systemProperty("lyrico.native.dir", nativeDir)
    // Where SchemaFidelityTest compares the generated desktop schema against the inherited one.
    systemProperty("lyrico.schema.dir", layout.projectDirectory.dir("schemas").asFile.absolutePath)
    systemProperty(
        "lyrico.android.schema.dir",
        layout.projectDirectory.dir("schemas-android").asFile.absolutePath,
    )
    // TagLib's vendored test audio files, used as tag read/write fixtures.
    systemProperty(
        "lyrico.audiotag.fixtures.dir",
        rootProject.layout.projectDirectory
            .dir("lyrico-audiotag/src/main/cpp/taglib/tests/data")
            .asFile.absolutePath,
    )
    // `DevLibrarySeederTest` rewrites the app's own data folder, so it only runs when asked for:
    //   ./gradlew :lyrico-app:test --tests "*DevLibrarySeederTest*" -Plyrico.seedDevLibrary=1
    // A project property rather than an environment variable, because the Gradle daemon (not the
    // calling shell) hands the environment to the test worker.
    systemProperty("lyrico.seedDevLibrary", providers.gradleProperty("lyrico.seedDevLibrary").getOrElse("0"))
    // `DevPluginSeederTest` installs a demo plugin into the app's own data folder for the same
    // reason, and is gated the same way:
    //   ./gradlew :lyrico-app:test --tests "*DevPluginSeederTest*" -Plyrico.seedDevPlugin=1
    systemProperty("lyrico.seedDevPlugin", providers.gradleProperty("lyrico.seedDevPlugin").getOrElse("0"))
}

compose.desktop {
    application {
        mainClass = "com.lonx.lyrico.MainKt"

        // Native libraries are built by scripts/build-native.ps1 (phase 1) and shipped next to the
        // app; the loader resolves them through the lyrico.native.dir system property, defaulting to
        // the per-OS directory under build/native.
        val nativeDir = rootProject.layout.projectDirectory.dir("build/native/windows-x64").asFile.absolutePath
        jvmArgs += listOf("-Dlyrico.native.dir=$nativeDir", "-Dlyrico.version=$version")

        // The dev start-route override (`Main` -> `LyricoNavHost` -> `desktopStartDestination`) exists so
        // a screen with no in-app entry point yet can still be captured in the real window. Gradle's own
        // `-D` flags land on the daemon, not on the app, so the value is forwarded here:
        //   ./gradlew :lyrico-app:run -Plyrico.start.route=plugin_manager
        providers.gradleProperty("lyrico.start.route").orNull?.takeIf { it.isNotBlank() }?.let { route ->
            jvmArgs += listOf("-Dlyrico.start.route=$route")
        }

        nativeDistributions {
            targetFormats(TargetFormat.Msi, TargetFormat.Exe)
            packageName = "Lyrico"
            // Placeholder until the packaging phase (PLAN.md phase 6) — jpackage rejects a version
            // with a suffix, and Windows wants x.y.z.w with the major >= 1.
            packageVersion = baseVersionName
            description = "Lyrico — audio tag editor"
            vendor = "Lonx"

            windows {
                menu = true
                shortcut = true
                // File association (.mp3/.flac/...) and per-user vs per-machine install scope are
                // decided in phase 6.
                dirChooser = true
            }

            modules("java.naming", "java.sql", "jdk.unsupported", "java.desktop")
        }
    }
}
