package com.lonx.lyrico.support

import com.lonx.lyrico.platform.FfmpegSidecar
import org.junit.Assume
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.nio.file.Files
import java.nio.file.Path
import java.util.concurrent.TimeUnit
import kotlin.math.PI
import kotlin.math.pow
import kotlin.math.roundToInt
import kotlin.math.sin

/**
 * Audio fixtures for the ReplayGain tests, written by hand instead of by ffmpeg.
 *
 * A fixture generated by ffmpeg would make the test's expectation depend on the same tool it is
 * checking. These WAV files carry known sample values, so the measurement can be compared against
 * arithmetic (a full-scale sine of amplitude `A` has RMS `A/√2`) rather than against another ffmpeg
 * run. ffmpeg is only used where the test genuinely needs a *codec* — mp3, flac, a file with no audio
 * stream — and for the independent integrated-loudness read-back in [integratedLufs].
 */
object AudioFixtures {

    const val SAMPLE_RATE: Int = 44100

    /** Linear amplitude for a level in dBFS: `-23 dBFS` is an RMS of `10^(-23/20)`. */
    fun rmsAmplitude(dbfs: Double): Double = 10.0.pow(dbfs / 20.0)

    /**
     * [seconds] of a sine at [frequencyHz], interleaved over [channels] identical channels.
     *
     * Every channel gets the same value, which is what makes the mono-versus-dual-mono test
     * meaningful: the two files differ in nothing but the channel count.
     */
    fun sine(
        seconds: Double,
        frequencyHz: Double = 1000.0,
        amplitude: Double = 1.0,
        channels: Int = 1,
        sampleRate: Int = SAMPLE_RATE,
    ): DoubleArray {
        val frames = (seconds * sampleRate).roundToInt()
        val samples = DoubleArray(frames * channels)
        for (frame in 0 until frames) {
            val value = amplitude * sin(2.0 * PI * frequencyHz * frame / sampleRate)
            for (channel in 0 until channels) {
                samples[frame * channels + channel] = value
            }
        }
        return samples
    }

    /** [seconds] of digital silence; the loudness of this is the floor case. */
    fun silence(
        seconds: Double,
        channels: Int = 1,
        sampleRate: Int = SAMPLE_RATE,
    ): DoubleArray = DoubleArray((seconds * sampleRate).roundToInt() * channels)

    /**
     * Writes a canonical RIFF/WAVE file holding [samples].
     *
     * [bitsPerSample] `32` writes IEEE float (format tag `0x0003`), `16` writes signed little-endian
     * shorts (tag `0x0001`) — the same layout ffmpeg emits for `pcm_s16le`.
     */
    fun writeWav(
        path: Path,
        samples: DoubleArray,
        channels: Int,
        sampleRate: Int = SAMPLE_RATE,
        bitsPerSample: Int = 32,
    ) {
        require(channels > 0) { "channels must be positive" }
        require(samples.size % channels == 0) { "sample array must hold whole frames" }
        require(bitsPerSample == 32 || bitsPerSample == 16) { "only 16 and 32 bit PCM are written" }

        val bytesPerSample = bitsPerSample / 8
        val dataSize = samples.size * bytesPerSample
        val formatTag = if (bitsPerSample == 32) 0x0003 else 0x0001

        val bytes = ByteBuffer.allocate(44 + dataSize).order(ByteOrder.LITTLE_ENDIAN)
        bytes.put("RIFF".toByteArray(Charsets.US_ASCII))
        bytes.putInt(36 + dataSize)
        bytes.put("WAVE".toByteArray(Charsets.US_ASCII))
        bytes.put("fmt ".toByteArray(Charsets.US_ASCII))
        bytes.putInt(16)
        bytes.putShort(formatTag.toShort())
        bytes.putShort(channels.toShort())
        bytes.putInt(sampleRate)
        bytes.putInt(sampleRate * channels * bytesPerSample)
        bytes.putShort((channels * bytesPerSample).toShort())
        bytes.putShort(bitsPerSample.toShort())
        bytes.put("data".toByteArray(Charsets.US_ASCII))
        bytes.putInt(dataSize)

        for (sample in samples) {
            if (bitsPerSample == 32) {
                bytes.putFloat(sample.toFloat())
            } else {
                bytes.putShort((sample * 32767.0).roundToInt().coerceIn(-32768, 32767).toShort())
            }
        }

        Files.createDirectories(path.parent)
        Files.write(path, bytes.array())
    }

    /** Frames in an interleaved array, i.e. sample instants rather than samples. */
    fun frameCount(samples: DoubleArray, channels: Int): Int = samples.size / channels

    // ------------------------------------------------------------------ ffmpeg driven fixtures

    /** The bundled sidecar, or a skipped test when it has not been fetched. */
    fun requireFfmpeg(): Path {
        val sidecar = FfmpegSidecar()
        Assume.assumeTrue(
            "ffmpeg sidecar not fetched; run scripts/fetch-ffmpeg.ps1",
            sidecar.isAvailable(),
        )
        return sidecar.locate()
    }

    data class FfmpegRun(val exitCode: Int, val stdout: ByteArray, val stderr: String) {
        val standardErrorText: String get() = stderr
    }

    /** Runs the sidecar to completion, draining both pipes concurrently so neither can block. */
    fun runFfmpeg(vararg args: String, timeoutSeconds: Long = 300): FfmpegRun {
        val executable = requireFfmpeg()
        val process = ProcessBuilder(listOf(executable.toString()) + args).start()
        process.outputStream.close()

        // Both pipes have to be drained at once: ffmpeg writes to one while the test waits on the
        // other, and a full pipe (64 KiB) blocks the child rather than failing it.
        val standardOutput = java.io.ByteArrayOutputStream()
        val drainOut = Thread {
            process.inputStream.use { it.copyTo(standardOutput) }
        }
        drainOut.isDaemon = true
        drainOut.start()

        val stderrText = process.errorStream.readBytes().toString(Charsets.UTF_8)
        process.waitFor(timeoutSeconds, TimeUnit.SECONDS)
        drainOut.join(5_000)

        return FfmpegRun(
            exitCode = process.exitValue(),
            stdout = standardOutput.toByteArray(),
            stderr = stderrText,
        )
    }

    /** Transcodes [source] into [target] with the caller's codec arguments. */
    fun transcode(source: Path, target: Path, vararg codecArgs: String): FfmpegRun {
        Files.createDirectories(target.parent)
        return runFfmpeg(
            "-nostdin", "-hide_banner", "-y",
            "-i", source.toString(),
            *codecArgs,
            target.toString(),
        )
    }

    /**
     * Integrated loudness of [file] as reported by **ffmpeg's own** `ebur128` filter.
     *
     * This is the independent read-back the scanner's numbers are compared against: a second,
     * differently-wired consumer of the BS.1770 algorithm. It validates the wiring this port is
     * responsible for (channel count, sample rate, format, chunk boundaries) rather than re-deriving
     * the algorithm — ffmpeg's filter links the same libebur128 the JNI bridge does, so agreement is
     * evidence about the plumbing, not an independent proof of the standard.
     *
     * @return `null` when ffmpeg prints no finite number (digital silence reads `-inf`).
     */
    fun integratedLufs(file: Path): Double? {
        val run = runFfmpeg(
            "-nostdin", "-hide_banner",
            "-i", file.toString(),
            "-map", "0:a:0",
            "-af", "ebur128=peak=sample",
            "-f", "null", "-",
        )
        return LUFS.findAll(run.stderr)
            .lastOrNull()
            ?.groupValues
            ?.get(1)
            ?.toDouble()
    }

    private val LUFS = Regex("""I:\s+(-?\d+(?:\.\d+)?)\s+LUFS""")
}
