#!/usr/bin/env python3
"""Port frontier: which java-tree files can move to the kotlin tree right now.

`port-closure.py` answers "what must move for *this* unit to compile" (transitive, from
an entry point). This answers the whole-tree inverse: for every file still in the
uncompiled `src/main/java` tree, are its project dependencies already satisfied by the
compiled `src/main/kotlin` tree?

The frontier is the set of files that can move *now*; the blockers say what the next
batch must finish first. It also reports **stale duplicates** -- java-tree files whose
relative path already exists in the kotlin tree. Those are leftovers from an earlier
port: the java tree is not compiled, so a stale copy either fails the build (fine) or,
worse, reads as the code that is running when it is not.

Usage:
    python scripts/port-frontier.py
    python scripts/port-frontier.py --prefix data/ --prefix viewmodel/
    python scripts/port-frontier.py --list-blocks
"""
from __future__ import annotations

import argparse
import os
import re
import sys

IMPORT_RE = re.compile(r"^\s*import\s+(?:static\s+)?([\w.]+)(?:\s+as\s+\w+)?\s*$")
PKG_RE = re.compile(r"^\s*package\s+([\w.]+)", re.M)

# Top-level declarations only -- the pattern must start at column 0. Allowing leading whitespace
# would also index members and local vals, and a same-package scan would then "find" a class
# called `title` or `uiState` and block a file that is perfectly portable.
# The trailing lookahead rejects an extension receiver: `fun String.toFoo()` would otherwise be
# recorded as a declaration named `String`, which poisons the whole package.
DECL_RE = re.compile(
    r"^(?:@\w+(?:\([^)]*\))?\s+)*"
    r"(?:public |internal |private |protected |open |abstract |sealed |data |enum |value"
    r" |annotation |external |expect |actual |suspend |inline )*"
    r"(?:class|interface|object|fun|val|var|typealias)\s+([A-Za-z_]\w*)(?!\s*[?.<])",
    re.M,
)

# The subset that names a *type*. Only these are used for the same-package reference scan:
# a bare word matching a same-package `fun`/`val` name is usually just a property that happens
# to share the name (`fun EditableField.title()` vs `x.title`), while an unresolved type is
# always a real compile error.
TYPE_DECL_RE = re.compile(
    r"^(?:@\w+(?:\([^)]*\))?\s+)*"
    r"(?:public |internal |private |protected |open |abstract |sealed |data |enum |value"
    r" |annotation |external |expect |actual )*"
    r"(?:class|interface|object|typealias)\s+([A-Za-z_]\w*)(?!\s*[?.<])",
    re.M,
)

# Extension declarations name themselves after a receiver type (`fun Modifier.blurSource()`),
# which the pattern above deliberately cannot see.
EXT_DECL_RE = re.compile(
    r"^(?:@\w+(?:\([^)]*\))?\s+)*"
    r"(?:public |internal |private |protected |open |abstract |inline |suspend |operator |tailrec )*"
    r"(?:fun|val|var)\s+(?:<[^>]*>\s*)?[\w.]+(?:<[^>]*>)?\.([A-Za-z_]\w*)",
    re.M,
)

# Generated by the Android build (AGP) or by this repo's own Gradle task; neither tree
# holds them, and on desktop `R` is replaced by Compose resources.
GENERATED = (
    "com.lonx.lyrico.R",
    "com.lonx.lyrico.BuildConfig",
    "com.lonx.lyrico.BuildInfo",
)
GENERATED_PREFIXES = ("com.lonx.lyrico.resources.",)

# Imports that mean "this file needs an edit before it can live in the kotlin tree".
ANDROID_PREFIXES = (
    "android.",
    "androidx.activity.",
    "androidx.work.",
    "androidx.documentfile.",
    "androidx.core.",
    "androidx.lifecycle.ViewModel",
    "androidx.lifecycle.viewmodel.",
    "androidx.navigation.",
    "androidx.paging.",
)

# Android-ish imports that are genuinely available on the desktop target.
DESKTOP_OK_PREFIXES = (
    "androidx.compose.",
    "androidx.datastore.preferences.core.",
    "androidx.room.",
    "androidx.sqlite.",
    "kotlinx.",
    "java.",
    "javax.",
    "kotlin.",
)


def walk_kt(root):
    out = []
    for dirpath, _dirs, names in os.walk(root):
        out += [os.path.join(dirpath, n) for n in names if n.endswith(".kt")]
    return sorted(out)


def read(path):
    with open(path, encoding="utf-8", errors="replace") as fh:
        return fh.read()


def index_tree(root):
    """FQCN -> path, indexed by file stem and by every declared top-level name."""
    out = {}
    for path in walk_kt(root):
        text = read(path)
        pkg = PKG_RE.search(text)
        if not pkg:
            continue
        pkg_name = pkg.group(1)
        out.setdefault(f"{pkg_name}.{os.path.basename(path)[:-3]}", path)
        for name in DECL_RE.findall(text) + EXT_DECL_RE.findall(text):
            out.setdefault(f"{pkg_name}.{name}", path)
    return out


def package_names(root):
    """package -> {type name: path}, for finding same-package references.

    A same-package reference carries no import line, so the import walk cannot see it: a file
    can look dependency-free while still naming a type that only exists in the other tree.
    Those are the ones that turn a "ready" verdict into a wasted move.
    """
    out = {}
    for path in walk_kt(root):
        text = read(path)
        pkg = PKG_RE.search(text)
        if not pkg:
            continue
        bucket = out.setdefault(pkg.group(1), {})
        for name in [os.path.basename(path)[:-3]] + TYPE_DECL_RE.findall(text):
            bucket.setdefault(name, path)
    return out


def resolve(import_, index):
    parts = import_.split(".")
    while len(parts) > 1:
        hit = index.get(".".join(parts))
        if hit:
            return hit
        parts.pop()
    return None


def main(argv):
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", default="lyrico-app/src/main")
    ap.add_argument("--prefix", action="append", default=[])
    ap.add_argument("--list-blocks", action="store_true")
    args = ap.parse_args(argv)

    src = args.src
    java_root = os.path.join(src, "java")
    kotlin_root = os.path.join(src, "kotlin")

    java_index = index_tree(java_root)
    kotlin_index = index_tree(kotlin_root)
    java_pkgs = package_names(java_root)

    prefixes = tuple(args.prefix) if args.prefix else ("",)
    stale, ready, blocked = [], [], []

    for path in walk_kt(java_root):
        rel = os.path.relpath(path, java_root).replace("\\", "/")
        if not any(f"/{rel}".startswith(f"/{p.strip('/')}") or f"/{p.strip('/')}/" in f"/{rel}"
                   for p in prefixes if p.strip("/") or p == ""):
            continue

        mirror = os.path.join(kotlin_root, rel)
        if os.path.exists(mirror):
            stale.append(rel)
            continue

        text = read(path)
        java_deps, android, generated = set(), set(), set()

        # Referenced without an import: same-package names the kotlin tree does not define.
        pkg = PKG_RE.search(text)
        if pkg:
            for name, src in java_pkgs.get(pkg.group(1), {}).items():
                if src == path or f"{pkg.group(1)}.{name}" in kotlin_index:
                    continue
                if re.search(rf"(?<![\w.]){re.escape(name)}\b", text):
                    java_deps.add(f"(same package) {name}")

        for imp in (m.group(1) for m in (IMPORT_RE.match(l) for l in text.splitlines()) if m):
            if imp.startswith(GENERATED) or imp.startswith(GENERATED_PREFIXES):
                generated.add(imp)
            elif imp.startswith("com.lonx.lyrico"):
                if resolve(imp, kotlin_index) is None:
                    hit = resolve(imp, java_index)
                    java_deps.add(imp if hit is None else os.path.relpath(hit, java_root).replace("\\", "/"))
            elif imp.startswith(ANDROID_PREFIXES):
                android.add(imp)
            elif imp.startswith(DESKTOP_OK_PREFIXES):
                continue

        if java_deps:
            blocked.append((rel, sorted(java_deps), len(android), len(generated)))
        else:
            ready.append((rel, len(android), len(generated)))

    print(f"java tree under {java_root}: {len(stale) + len(ready) + len(blocked)} files"
          f" (prefixes: {', '.join(p or '<all>' for p in prefixes)})\n")

    print(f"== stale duplicates: already ported, delete the java copy ({len(stale)}) ==")
    for rel in stale:
        print(f"  {rel}")

    print(f"\n== frontier: dependencies satisfied, can move now ({len(ready)}) ==")
    for rel, n, gen in sorted(ready, key=lambda r: (r[1], r[2], r[0])):
        flags = ("  [ANDROID]" if n else "") + (f"  [{gen} resource refs]" if gen else "")
        print(f"  {rel}{flags}")

    print(f"\n== blocked: still waiting on java-tree files ({len(blocked)}) ==")
    for rel, deps, n, gen in sorted(blocked, key=lambda b: (len(b[1]), b[0])):
        flag = ("  [ANDROID]" if n else "") + (f"  [{gen} resource refs]" if gen else "")
        if args.list_blocks:
            print(f"  {rel}{flag}")
            for dep in deps:
                print(f"      <- {dep}")
        else:
            print(f"  {rel}{flag}  ({len(deps)} dep{'s' if len(deps) != 1 else ''})")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
